# Generated by Django 4.2.3 on 2023-07-08 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='rest_app.color'),
        ),
    ]
